### ISSUE TITLE
Move the site off Heroku

### ISSUE THREAD

**Issue by darrencauthon** [kcruby/newkcruby#8]
Discussion started here:

https://github.com/darrencauthon/newkcruby/issues/6

My plan:  
- [ ] Set up a $5 Digital Ocean Server.
- [ ] Set the site up to be hosted there.
- [ ] Enable page caching to keep the site static.
- [ ] Daily job to refresh the cache.
- [ ] Switch the DNS.
- [ ] Set up Pingdom monitoring.

**Comment by rossfuhrman** [comment]
Closed. Won't fix. 😛
